[workspace]
members = [
    "leaf",
    "leaf-android",
    "leaf-bin",
    "leaf-ffi",
    "leaf-plugins/shadowsocks",
]
default-members = ["leaf-bin"]

[patch.crates-io]
ntapi = { path = "patches/ntapi-0.3.7" }
tokio = { path = "patches/tokio-1.48.0" }

[patch."https://github.com/eycorsican/netstack-lwip.git"]
netstack-lwip = { path = "patches/netstack-lwip-0.3.1" }

[profile.release]
opt-level = 3
lto = true
# codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"
